In [420]:
import numpy as np
import pandas as pd

In [421]:
input = np.array([1,2,3])
weights = np.random.randn(3, 3) * 0.01
bias = np.zeros((1,3))

output=np.dot(input,weights)+bias
output

array([[-0.01163921,  0.0020616 , -0.00464584]])

Activation function

In [422]:
class ReluAct:
    def __init__(self):
        pass
    def forward(self,inputs):
         self.output=np.maximum(0,inputs)
         return self.output

In [423]:
input = np.array([1,2,3])
weights = np.random.randn(3, 3) * 0.01
bias = np.zeros((1,3))

output=np.dot(input,weights)+bias
print(output)
output = ReLu(output)
output

[[ 0.00504177  0.05072286 -0.03281478]]


array([[0.00504177, 0.05072286, 0.        ]])

In [424]:
input = np.array([[1,2,3],[3,4,5],[6,8,1]]) # 3x3
weights = np.random.randn(3, 3) * 0.01 # 3x3
bias = np.zeros((1,3))

output=np.dot(input,weights)+bias
print(output)
output = ReLu(output)
output

[[ 0.01739508  0.00963517 -0.02268112]
 [ 0.02960449  0.0149406  -0.05912724]
 [-0.00034063  0.01702014 -0.0841906 ]]


array([[0.01739508, 0.00963517, 0.        ],
       [0.02960449, 0.0149406 , 0.        ],
       [0.        , 0.01702014, 0.        ]])

# Batch inputs

In [425]:
input = np.array([[1,2,3],[3,4,5],[6,8,1]]) # 3x3
weights = np.random.randn(3, 3) * 0.01 # 3x3
bias = np.zeros((1,3))

output=np.dot(input,weights)+bias
print(output)
output = ReLu(output)
output

[[-0.02356214  0.04055645 -0.02546388]
 [-0.04871708  0.07902515 -0.04168737]
 [-0.06762508  0.07214086 -0.06880115]]


array([[0.        , 0.04055645, 0.        ],
       [0.        , 0.07902515, 0.        ],
       [0.        , 0.07214086, 0.        ]])

# Multiple Layers

In [426]:
input = np.array([[1,2,3],[3,4,5],[6,8,1]]) # 3x3
# Layer 1
weights1 = np.random.randn(3, 3) * 0.01 # 3x3
bias1 = np.zeros((1,3))

# Layer 2
weights2 = np.random.randn(3, 3) * 0.01 # 3x3
bias2 = np.zeros((1,3))

layer1=np.dot(input,weights1)+bias1
layer1 = ReLu(layer1)
print(layer1)

layer2=np.dot(layer1,weights2)+bias2
output = ReLu(layer2)

print(output)


[[0.03038941 0.10704594 0.02870362]
 [0.0638935  0.16587525 0.08237708]
 [0.09261033 0.03105966 0.21539809]]
[[0.         0.         0.        ]
 [0.         0.         0.        ]
 [0.         0.00175329 0.00078726]]


# Class of NN

In [427]:
class Dense:
    def __init__(self,inputs,neurons):
        self.weights=np.random.randn(inputs,neurons)
        self.bias=np.zeros((1,neurons))
    def forward(self,input):
        self.output = np.dot(input,self.weights)+self.bias
        return self.output


# Softmax

In [428]:
class Softmax:
    def __init__(self):
        pass
    def forward(self,input):
        max_row = np.max(input,axis=1,keepdims=True)
        normalize_row = input-max_row
        expo_max = np.sum(np.exp(normalize_row),axis=1,keepdims=True)
        expo_values = np.exp(normalize_row)/expo_max
        self.output = expo_values
        return self.output


        

# Cross Entropy Loss

In [429]:
class Cross_entropyLoss:
    def __init__(self):
        pass
    def forward(self, y_pred, y_true):
        y_pred_clipped = np.clip(y_pred, 1e-12, 1.0)
        sample_losses = -np.sum(y_true * np.log(y_pred_clipped), axis=1)
       
        self.output = np.mean(sample_losses)
        return self.output


In [430]:
y = np.array([
    [1, 0, 0],  # sample 1 → class 0
    [0, 1, 0],  # sample 2 → class 1
    [0, 0, 1]   # sample 3 → class 2
])


In [431]:
cs = Cross_entropyLoss()
cs.forward(output,y)

np.float64(20.80299711621895)

# Dense Layer with Activation, Softmax, Loss function

In [432]:
input = np.array([[1,2,3],[3,4,5],[6,8,1]]) # 3x3
# Layer 1
weights1 = np.random.randn(3, 3) * 0.01 # 3x3
bias1 = np.zeros((1,3))

# Layer 2
weights2 = np.random.randn(3, 3) * 0.01 # 3x3
bias2 = np.zeros((1,3))

layer1=np.dot(input,weights1)+bias1
layer1 = ReLu(layer1)

layer2=np.dot(layer1,weights2)+bias2

actSoft = Softmax()
actSoft.forward(layer2)

lossFun = Cross_entropyLoss()
lossFun.forward(actSoft.output,[[1,0,0],[0,1,0],[1,0,0]])


print(lossFun.output)


1.0989186875073964


In [ ]:
X = np.array([
    [1, 2, 3],
    [3, 4, 5],
    [6, 8, 1]
])

# True labels (3 classes, one-hot)
# Let's say sample 1 → class 0, sample 2 → class 1, sample 3 → class 2
y = np.array([
    [1, 0, 0],  # sample 1 → class 0
    [0, 1, 0],  # sample 2 → class 1
    [0, 0, 1]   # sample 3 → class 2
])

layer1 = Dense(3,3)
layer2 = Dense(3,3)

largest_loss = 99999
best_weights1 = layer1.weights.copy()
best_bias1 = layer1.bias.copy()
best_weights2 = layer2.weights.copy()
best_bias2 = layer2.bias.copy()

reluAct = ReluAct()
actSoft = Softmax()
lossFun = Cross_entropyLoss()

for i in range(1000000):
    layer1.weights = 0.05 * np.random.randn(3,3)
    layer1.bias = np.zeros((1,3))
    layer2.weights = 0.05 *np.random.randn(3,3)
    layer2.bias = np.zeros((1,3))

    output_layer1 = layer1.forward(X)
    output_relu = reluAct.forward(output_layer1)
    output_layer2 = layer2.forward(output_relu)
    actSoft_output = actSoft.forward(output_layer2)
    lossFun_output = lossFun.forward(actSoft_output,y)
    
    # actSoft_output.output has shape (batch_size, n_classes)
    pred_classes = np.argmax(actSoft_output, axis=1)
    true_classes = np.argmax(y, axis=1)

    acc = np.mean(pred_classes == true_classes)

    
    if lossFun_output < largest_loss:
        print("New Less loss has been found at: ",i, " loss ",lossFun_output, " Accuracy ", acc)
        largest_loss=lossFun_output
        best_weights1 = layer1.weights.copy()
        best_bias1 = layer1.bias.copy()
        best_weights2 = layer2.weights.copy()
        best_bias2 = layer2.bias.copy()

    



New Less loss has been found at:  0  loss  1.0986062984079403  Accuracy  0.3333333333333333
New Less loss has been found at:  1  loss  1.0858992478809393  Accuracy  0.3333333333333333
New Less loss has been found at:  53  loss  1.0642545714747251  Accuracy  0.3333333333333333
New Less loss has been found at:  13682  loss  1.0621434976867528  Accuracy  0.3333333333333333
New Less loss has been found at:  19031  loss  1.0572398383257238  Accuracy  0.3333333333333333
New Less loss has been found at:  48955  loss  1.0542450403402746  Accuracy  0.3333333333333333
New Less loss has been found at:  110839  loss  1.0509035513214162  Accuracy  0.3333333333333333
New Less loss has been found at:  222298  loss  1.048888896269481  Accuracy  0.3333333333333333
New Less loss has been found at:  526291  loss  1.0459575212052932  Accuracy  0.3333333333333333
New Less loss has been found at:  569220  loss  1.0451822199802434  Accuracy  0.3333333333333333
New Less loss has been found at:  702429  loss  

In [434]:
print(actSoft_output)

[[0.3353103  0.32767604 0.33701365]
 [0.33376237 0.32276329 0.34347434]
 [0.31968218 0.31635132 0.3639665 ]]


In [435]:
y

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])