In [76]:
import numpy as np
import pandas as pd

In [77]:
input = np.array([1,2,3])
weights = np.random.randn(3, 3) * 0.01
bias = np.zeros((1,3))

output=np.dot(input,weights)+bias
output

array([[ 0.02652128, -0.0298474 , -0.00894195]])

Activation function

In [78]:
class ReluAct:
    def __init__(self):
        pass
    def forward(self,inputs):
         self.output=np.maximum(0,inputs)
         return self.output

In [79]:
# input = np.array([1,2,3])
# weights = np.random.randn(3, 3) * 0.01
# bias = np.zeros((1,3))

# output=np.dot(input,weights)+bias
# print(output)
# output = ReLu(output)
# output

In [80]:
# input = np.array([[1,2,3],[3,4,5],[6,8,1]]) # 3x3
# weights = np.random.randn(3, 3) * 0.01 # 3x3
# bias = np.zeros((1,3))

# output=np.dot(input,weights)+bias
# print(output)
# output = ReLu(output)
# output

# Batch inputs

In [81]:
# input = np.array([[1,2,3],[3,4,5],[6,8,1]]) # 3x3
# weights = np.random.randn(3, 3) * 0.01 # 3x3
# bias = np.zeros((1,3))

# output=np.dot(input,weights)+bias
# print(output)
# output = ReLu(output)
# output

# Multiple Layers

In [82]:
# input = np.array([[1,2,3],[3,4,5],[6,8,1]]) # 3x3
# # Layer 1
# weights1 = np.random.randn(3, 3) * 0.01 # 3x3
# bias1 = np.zeros((1,3))

# # Layer 2
# weights2 = np.random.randn(3, 3) * 0.01 # 3x3
# bias2 = np.zeros((1,3))

# layer1=np.dot(input,weights1)+bias1
# layer1 = ReLu(layer1)
# print(layer1)

# layer2=np.dot(layer1,weights2)+bias2
# output = ReLu(layer2)

# print(output)


# Class of NN

In [ ]:
class Dense:
    def __init__(self,inputs,neurons):
        self.weights=0.01*np.random.randn(inputs,neurons)
        self.bias=np.zeros((1,neurons))
    def forward(self,input):
        self.output = np.dot(input,self.weights)+self.bias
        return self.output


# Softmax

In [84]:
class Softmax:
    def __init__(self):
        pass
    def forward(self,input):
        max_row = np.max(input,axis=1,keepdims=True)
        normalize_row = input-max_row
        expo_max = np.sum(np.exp(normalize_row),axis=1,keepdims=True)
        expo_values = np.exp(normalize_row)/expo_max
        self.output = expo_values
        return self.output


        

# Cross Entropy Loss

In [85]:
class Cross_entropyLoss:
    def __init__(self):
        pass
    def forward(self, y_pred, y_true):
        y_pred_clipped = np.clip(y_pred, 1e-12, 1.0)
        sample_losses = -np.sum(y_true * np.log(y_pred_clipped), axis=1)
       
        self.output = np.mean(sample_losses)
        return self.output


In [86]:
y = np.array([
    [1, 0, 0],  # sample 1 → class 0
    [0, 1, 0],  # sample 2 → class 1
    [0, 0, 1]   # sample 3 → class 2
])


In [87]:
cs = Cross_entropyLoss()
cs.forward(output,y)

np.float64(19.63061671445764)

# Dense Layer with Activation, Softmax, Loss function

In [ ]:
input = np.array([[1,2,3],[3,4,5],[6,8,1]]) # 3x3
# Layer 1
weights1 = np.random.randn(3, 3) * 0.01 # 3x3
bias1 = np.zeros((1,3))

# Layer 2
weights2 = np.random.randn(3, 3) * 0.01 # 3x3
bias2 = np.zeros((1,3))

layer1=np.dot(input,weights1)+bias1
# layer1 = ReLu(layer1)


actSoft = Softmax()
actSoft.forward(layer1)

lossFun = Cross_entropyLoss()
lossFun.forward(actSoft.output,[[1,0,0],[0,1,0],[1,0,0]])



print(lossFun.output)


1.0981175686269748


In [ ]:
import numpy as np

def ReluAct(x):
    return np.maximum(0, x)

def derivativeRelu(x):
    return (x > 0).astype(float)

inputs = np.array([10.0, 20.0, 30.0, 40.0])   
weights = np.random.randn(3, 4)              
biases = np.zeros(3)                        
target = 5.0
lr = 0.001


dy_da = np.ones(3)

for it in range(100):

    z = weights.dot(inputs) + biases        
    a = ReluAct(z)                        
    y = a.sum()                           
    loss = (y - target)**2

    dL_dy = 2.0 * (y)             

    da_dz = derivativeRelu(z)              
    dL_da = dL_dy * dy_da                  
    dL_dz = dL_da * da_dz                 

    dL_dW = dL_dz[:, np.newaxis] * inputs[np.newaxis, :]   

    dL_db = dL_dz.copy()                  

    weights -= lr * dL_dW
    biases  -= lr * dL_db

    if it % 10 == 0:
        print(f"iter {it:03d}  loss {loss:.6f}  y {y:.4f}")


# Dense Layer + Backward 

In [ ]:
class ReluAct:
    def forward(self, x):
        self.input = x
        self.output = np.maximum(0, x)
        return self.output
    
    def backward(self, dL_dout):
        dL_dinput = dL_dout * (self.input > 0).astype(float)
        return dL_dinput


In [ ]:

class CrossEntropyLoss:
    def forward(self, y_pred, y_true):
        y_pred_clipped = np.clip(y_pred, 1e-12, 1.0)
        sample_losses = -np.sum(y_true * np.log(y_pred_clipped), axis=1)
        self.y_pred = y_pred
        self.y_true = y_true
        return np.mean(sample_losses)
    
    def backward(self):
        n_samples = self.y_true.shape[0]
        dL_dy = (self.y_pred - self.y_true) / n_samples
        return dL_dy


In [ ]:
class Softmax:
    def forward(self, x):
        max_row = np.max(x, axis=1, keepdims=True)
        normalize_row = x - max_row
        expo = np.exp(normalize_row)
        self.output = expo / np.sum(expo, axis=1, keepdims=True)
        return self.output
   

In [ ]:
import numpy as np

class Dense:
    def __init__(self, input_dim, output_dim):
        self.weights = np.random.randn(output_dim, input_dim) * 0.01
        self.biases = np.zeros(output_dim)
    
    def forward(self, x):
        self.input = x           
        self.output = x @ self.weights.T + self.biases  
        return self.output

    def backward(self, dL_dout):
        self.dL_dW = dL_dout.T @ self.input  
        self.dL_db = np.sum(dL_dout, axis=0) 
        dL_dinput = dL_dout @ self.weights  
        
        return dL_dinput


In [ ]:

# Test data
inputs = np.array([[10.0, 20.0, 30.0, 40.0]]) 
target = np.array([[1.0, 0.0, 0.0]])           
lr = 0.001

# Initialize layers
dense = Dense(input_dim=4, output_dim=3)
relu = ReluAct()
softmax = Softmax()
loss_func = CrossEntropyLoss()

# Training loop
for it in range(100):
    # Forward pass
    z = dense.forward(inputs)           # (1, 3)
    a = relu.forward(z)                 # (1, 3)
    y_pred = softmax.forward(a)         # (1, 3) - no transpose!
    loss = loss_func.forward(y_pred, target)
    
    # Backward pass - combined softmax + cross-entropy gradient
    dL = loss_func.backward()           # (1, 3)
    dL = relu.backward(dL)              # (1, 3)
    dL = dense.backward(dL)             # (1, 4)
    
    # Update parameters
    dense.weights -= lr * dense.dL_dW
    dense.biases  -= lr * dense.dL_db

    if it % 10 == 0:
        print(f"iter {it:03d}  loss {loss:.6f}  y_pred {y_pred[0]}")


iter 000  loss 0.895443  y_pred [0.40842677 0.29650596 0.29506728]
iter 010  loss 0.030667  y_pred [0.9697986 0.0151007 0.0151007]
iter 020  loss 0.015885  y_pred [0.98424052 0.00787974 0.00787974]
iter 030  loss 0.010734  y_pred [0.98932323 0.00533838 0.00533838]
iter 040  loss 0.008110  y_pred [0.99192326 0.00403837 0.00403837]
iter 050  loss 0.006518  y_pred [0.99350363 0.00324819 0.00324819]
iter 060  loss 0.005449  y_pred [0.99456616 0.00271692 0.00271692]
iter 070  loss 0.004681  y_pred [0.99532968 0.00233516 0.00233516]
iter 080  loss 0.004104  y_pred [0.9959049  0.00204755 0.00204755]
iter 090  loss 0.003653  y_pred [0.99635386 0.00182307 0.00182307]


In [20]:
import numpy as np

z = np.array([2.0, 1.0, 0.1])
y_pred = np.exp(z - np.max(z)) / np.sum(np.exp(z - np.max(z)))
y_true = np.array([1, 0, 0])  # class 0


In [21]:
dL_dy = -y_true / y_pred


In [22]:
n = y_pred.size
J = np.zeros((n, n))
for i in range(n):
    for j in range(n):
        if i == j:
            J[i, j] = y_pred[i] * (1 - y_pred[i])
        else:
            J[i, j] = -y_pred[i] * y_pred[j]


In [23]:
dL_dz = J @ dL_dy
print(dL_dz)


[-0.34099886  0.24243297  0.09856589]


In [24]:
y_pred - y_true

array([-0.34099886,  0.24243297,  0.09856589])