In [327]:
import numpy as np
import pandas as pd

In [328]:
input = np.array([1,2,3])
weights = np.random.randn(3, 3) * 0.01
bias = np.zeros((1,3))

output=np.dot(input,weights)+bias
output

array([[-0.01669244, -0.00515437,  0.01603616]])

Activation function

In [329]:
class ReluAct:
    def __init__(self):
        pass
    def forward(self,inputs):
         self.output=np.maximum(0,inputs)
         return self.output

In [330]:
input = np.array([1,2,3])
weights = np.random.randn(3, 3) * 0.01
bias = np.zeros((1,3))

output=np.dot(input,weights)+bias
print(output)
output = ReLu(output)
output

[[ 0.04449274 -0.07432865  0.01881836]]


array([[0.04449274, 0.        , 0.01881836]])

In [331]:
input = np.array([[1,2,3],[3,4,5],[6,8,1]]) # 3x3
weights = np.random.randn(3, 3) * 0.01 # 3x3
bias = np.zeros((1,3))

output=np.dot(input,weights)+bias
print(output)
output = ReLu(output)
output

[[ 0.00091892  0.02170107 -0.0004759 ]
 [-0.00204673  0.06165744 -0.01380166]
 [-0.02979859  0.12972234 -0.10188826]]


array([[0.00091892, 0.02170107, 0.        ],
       [0.        , 0.06165744, 0.        ],
       [0.        , 0.12972234, 0.        ]])

# Batch inputs

In [332]:
input = np.array([[1,2,3],[3,4,5],[6,8,1]]) # 3x3
weights = np.random.randn(3, 3) * 0.01 # 3x3
bias = np.zeros((1,3))

output=np.dot(input,weights)+bias
print(output)
output = ReLu(output)
output

[[ 0.0211063  -0.03320323  0.00794255]
 [ 0.04193656 -0.06290099  0.02210576]
 [ 0.11830898 -0.06324467  0.06486607]]


array([[0.0211063 , 0.        , 0.00794255],
       [0.04193656, 0.        , 0.02210576],
       [0.11830898, 0.        , 0.06486607]])

# Multiple Layers

In [333]:
input = np.array([[1,2,3],[3,4,5],[6,8,1]]) # 3x3
# Layer 1
weights1 = np.random.randn(3, 3) * 0.01 # 3x3
bias1 = np.zeros((1,3))

# Layer 2
weights2 = np.random.randn(3, 3) * 0.01 # 3x3
bias2 = np.zeros((1,3))

layer1=np.dot(input,weights1)+bias1
layer1 = ReLu(layer1)
print(layer1)

layer2=np.dot(layer1,weights2)+bias2
output = ReLu(layer2)

print(output)


[[0.         0.02334242 0.        ]
 [0.         0.04390044 0.        ]
 [0.         0.06916325 0.        ]]
[[0.         0.         0.0001153 ]
 [0.         0.         0.00021685]
 [0.         0.         0.00034163]]


# Class of NN

In [334]:
class Dense:
    def __init__(self,inputs,neurons):
        self.weights=np.random.randn(inputs,neurons)
        self.bias=np.zeros((1,neurons))
    def forward(self,input):
        self.output = np.dot(input,self.weights)+self.bias
        return self.output


# Softmax

In [335]:
class Softmax:
    def __init__(self):
        pass
    def forward(self,input):
        max_row = np.max(input,axis=1,keepdims=True)
        normalize_row = input-max_row
        expo_max = np.sum(np.exp(normalize_row),axis=1,keepdims=True)
        expo_values = np.exp(normalize_row)/expo_max
        self.output = expo_values


        

# Cross Entropy Loss

In [ ]:
class Cross_entropyLoss:
    def __init__(self):
        pass
    def forward(self, y_pred, y_true):
        y_pred_clipped = np.clip(y_pred, 1e-12, 1.0)
        sample_losses = -np.sum(y_true * np.log(y_pred_clipped), axis=1)
       
        self.output = np.mean(sample_losses)
        return self.output


In [337]:
y = np.array([
    [1, 0, 0],  # sample 1 → class 0
    [0, 1, 0],  # sample 2 → class 1
    [0, 0, 1]   # sample 3 → class 2
])


In [338]:
cs = Cross_entropyLoss()
cs.forward(output,y)

[27.63102112 27.63102112  7.98177974]


np.float64(21.08127399083535)

# Dense Layer with Activation, Softmax, Loss function

In [339]:
input = np.array([[1,2,3],[3,4,5],[6,8,1]]) # 3x3
# Layer 1
weights1 = np.random.randn(3, 3) * 0.01 # 3x3
bias1 = np.zeros((1,3))

# Layer 2
weights2 = np.random.randn(3, 3) * 0.01 # 3x3
bias2 = np.zeros((1,3))

layer1=np.dot(input,weights1)+bias1
layer1 = ReLu(layer1)

layer2=np.dot(layer1,weights2)+bias2

actSoft = Softmax()
actSoft.forward(layer2)

lossFun = Cross_entropyLoss()
lossFun.forward(actSoft.output,[[1,0,0],[0,1,0],[1,0,0]])


print(lossFun.output)


[1.0988251  1.09846385 1.09959485]
1.0989612687599504


In [340]:
X = np.array([
    [1, 2, 3],
    [3, 4, 5],
    [6, 8, 1]
])

# True labels (3 classes, one-hot)
# Let's say sample 1 → class 0, sample 2 → class 1, sample 3 → class 2
y = np.array([
    [1, 0, 0],  # sample 1 → class 0
    [0, 1, 0],  # sample 2 → class 1
    [0, 0, 1]   # sample 3 → class 2
])

layer1 = Dense(3,3)
layer2 = Dense(3,3)

largest_loss = 99999
best_weights1 = layer1.weights.copy()
best_bias1 = layer1.bias.copy()
best_weights2 = layer2.weights.copy()
best_bias2 = layer2.bias.copy()

reluAct = ReluAct()
actSoft = Softmax()
lossFun = Cross_entropyLoss()

for i in range(1000):
    layer1.weights = 0.05 * np.random.randn(3,3)
    layer1.bias = np.zeros((1,3))
    layer2.weights = 0.05 *np.random.randn(3,3)
    layer2.bias = np.zeros((1,3))

    output_layer1 = layer1.forward(X)
    output_relu = reluAct.forward(output_layer1)
    output_layer2 = layer2.forward(output_relu)
    actSoft_output = actSoft.forward(output_layer2)
    lossFun_output = lossFun.forward(actSoft_output)
    
    # actSoft_output.output has shape (batch_size, n_classes)
    pred_classes = np.argmax(actSoft_output.output, axis=1)
    true_classes = np.argmax(y, axis=1)

    acc = np.mean(pred_classes == true_classes)

    
    if lossFun_output < largest_loss:
        print("New Less loss has been found at: ",i, " loss ",lossFun_output, " Accuracy ", acc)
        largest_loss=lossFun_output
        best_weights1 = layer1.weights.copy()
        best_bias1 = layer1.bias.copy()
        best_weights2 = layer2.weights.copy()
        best_bias2 = layer2.bias.copy()

    



TypeError: Cross_entropyLoss.forward() missing 1 required positional argument: 'y_true'