In [184]:
import numpy as np
import pandas as pd

In [185]:
input = np.array([1,2,3])
weights = np.random.randn(3, 3) * 0.01
bias = np.zeros((1,3))

output=np.dot(input,weights)+bias
output

array([[ 0.0520432 , -0.02615373,  0.01432623]])

Activation function

In [186]:
def ReLu(x):
    return np.maximum(0,x)

In [187]:
input = np.array([1,2,3])
weights = np.random.randn(3, 3) * 0.01
bias = np.zeros((1,3))

output=np.dot(input,weights)+bias
print(output)
output = ReLu(output)
output

[[-0.02475058  0.01373153  0.05879445]]


array([[0.        , 0.01373153, 0.05879445]])

In [188]:
input = np.array([[1,2,3],[3,4,5],[6,8,1]]) # 3x3
weights = np.random.randn(3, 3) * 0.01 # 3x3
bias = np.zeros((1,3))

output=np.dot(input,weights)+bias
print(output)
output = ReLu(output)
output

[[-0.02615576  0.05656393 -0.04245446]
 [-0.06773479  0.11706449 -0.08202978]
 [-0.15542107  0.13095274 -0.06235298]]


array([[0.        , 0.05656393, 0.        ],
       [0.        , 0.11706449, 0.        ],
       [0.        , 0.13095274, 0.        ]])

# Batch inputs

In [189]:
input = np.array([[1,2,3],[3,4,5],[6,8,1]]) # 3x3
weights = np.random.randn(3, 3) * 0.01 # 3x3
bias = np.zeros((1,3))

output=np.dot(input,weights)+bias
print(output)
output = ReLu(output)
output

[[ 0.02063102  0.02237544 -0.04038072]
 [ 0.02412115  0.05185784 -0.06201511]
 [-0.14522072  0.09209535  0.01413768]]


array([[0.02063102, 0.02237544, 0.        ],
       [0.02412115, 0.05185784, 0.        ],
       [0.        , 0.09209535, 0.01413768]])

# Multiple Layers

In [190]:
input = np.array([[1,2,3],[3,4,5],[6,8,1]]) # 3x3
# Layer 1
weights1 = np.random.randn(3, 3) * 0.01 # 3x3
bias1 = np.zeros((1,3))

# Layer 2
weights2 = np.random.randn(3, 3) * 0.01 # 3x3
bias2 = np.zeros((1,3))

layer1=np.dot(input,weights1)+bias1
layer1 = ReLu(layer1)
print(layer1)

layer2=np.dot(layer1,weights2)+bias2
output = ReLu(layer2)

print(output)


[[0.03122658 0.0541154  0.00170626]
 [0.06292448 0.09935784 0.01466547]
 [0.04565095 0.02721606 0.00814456]]
[[0.00073771 0.         0.        ]
 [0.00137034 0.         0.        ]
 [0.00071292 0.         0.        ]]


# Class of NN

In [191]:
class Dense:
    def __init__(self,inputs,neurons):
        self.weights=np.random.randn((inputs,neurons))
        self.bias=np.zeros((1,neurons))
    def forward(self,input):
        self.output = np.dot(input,self.weights)+self.bias


# Softmax

In [192]:
class Softmax:
    def __init__(self):
        pass
    def forward(self,input):
        max_row = np.max(input,axis=1,keepdims=True)
        normalize_row = input-max_row
        expo_max = np.sum(np.exp(normalize_row),axis=1,keepdims=True)
        expo_values = np.exp(normalize_row)/expo_max
        self.output = expo_values


        

# Cross Entropy Loss

In [193]:
class Cross_entropyLoss:
    def __init__(self):
        pass
    def forward(self, y_pred, y_true):
        y_pred_clipped = np.clip(y_pred, 1e-12, 1.0)
        sample_losses = -np.sum(y_true * np.log(y_pred_clipped), axis=1)
        self.output = np.mean(sample_losses)
        return self.output


# Dense Layer with Activation, Softmax, Loss function

In [194]:
input = np.array([[1,2,3],[3,4,5],[6,8,1]]) # 3x3
# Layer 1
weights1 = np.random.randn(3, 3) * 0.01 # 3x3
bias1 = np.zeros((1,3))

# Layer 2
weights2 = np.random.randn(3, 3) * 0.01 # 3x3
bias2 = np.zeros((1,3))

layer1=np.dot(input,weights1)+bias1
layer1 = ReLu(layer1)

layer2=np.dot(layer1,weights2)+bias2

actSoft = Softmax()
actSoft.forward(layer2)

lossFun = Cross_entropyLoss()
lossFun.forward(actSoft.output,[[1,0,0],[0,1,0],[1,0,0]])


print(lossFun.output)


1.0993695636733738
